# Based on https://github.com/valiantlynx/ollama-docker/blob/main/docker-compose.yml

services:
  app:
    build: .
    #Uncomment to enable public server on 7869 port, or use it under a local proxy like NPM
    # ports:
    #   - 8000:8000
    #   - 5678:5678
    volumes:
      - .:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    depends_on:
      - ollama
      - ollama-webui
    networks:
      ollama-docker:
      # proxy:
      #   ipv4_address: 192.168.1.11

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    #Uncomment to enable public server on 7869 port, or use it under a local proxy like NPM
    # ports:
    #   - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      ollama-docker:
        ipv4_address: 172.18.0.2

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://172.18.0.2:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      ollama-docker:
        
      proxy:
        ipv4_address: 192.168.1.12

networks:
  ollama-docker:
    name: proxy
    ipam:
      driver: default

      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
  proxy:
    external: true
    
  